# ─── Scout.io Quick-Start Installer (Windows / PowerShell) ───────────────────
# Brings up a minimal Scout.io stack (Postgres+pgvector, Redis, backend API,
# Celery worker, Next.js dashboard) with a seeded demo chatbot.
#
#   .\scripts\install.ps1
#
# Requires: Docker Desktop (with Compose v2), git, and an internet connection.
# No .env editing needed — demo defaults are generated for you. LLM/embedding
# calls run in deterministic MOCK_LLM mode unless you set OPENAI_API_KEY /
# ANTHROPIC_API_KEY in backend\.env afterwards and restart.
[CmdletBinding()]
param(
  [string]$RepoUrl = "https://github.com/VForge-Tech/Scout.io.git",
  [string]$RepoDir = "scout.io"
)

$ErrorActionPreference = "Stop"

$ComposeFile = "docker/docker-compose.quickstart.yml"
$ComposeProfile = "quick-start"
$DemoEmail = "demo@scout.io"
$DemoPassword = "DemoPass123!"

function Write-Log { Write-Host "`n==> $args" -ForegroundColor Green }
function Write-Warn { Write-Host "[!] $args" -ForegroundColor Yellow }
function Die { Write-Host "[!] $args" -ForegroundColor Red; exit 1 }

# ─── Prerequisite checks ─────────────────────────────────────────────────────
Write-Log "Checking prerequisites..."
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
  Die "Docker not found. Install Docker Desktop first: https://www.docker.com/products/docker-desktop/"
}
docker compose version *> $null
if ($LASTEXITCODE -ne 0) {
  Die "Docker Compose plugin (v2) not found. Enable it in Docker Desktop settings (Settings > General > 'Use Docker Compose V2')."
}
if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
  Die "git not found. Install it from https://git-scm.com/ , or run this script from an existing checkout."
}

# ─── Locate / clone the repo ─────────────────────────────────────────────────
$RootDir = $PSScriptRoot | Split-Path -Parent
if (Test-Path (Join-Path $RootDir $ComposeFile)) {
  Write-Log "Using current checkout: $RootDir"
  Set-Location $RootDir
} elseif (Test-Path $RepoDir) {
  Write-Log "Updating existing checkout in $RepoDir"
  git -C $RepoDir pull --ff-only
  Set-Location $RepoDir
} else {
  Write-Log "Cloning Scout.io from $RepoUrl"
  git clone --depth 1 $RepoUrl $RepoDir
  if ($LASTEXITCODE -ne 0) { Die "Clone failed. Check the URL or your network." }
  Set-Location $RepoDir
}

# ─── Generate .env files ─────────────────────────────────────────────────────
function New-Secret {
  try {
    $bytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    return ($bytes | ForEach-Object { $_.ToString("x2") }) -join ""
  } catch {
    return [guid]::NewGuid().ToString("N") + [guid]::NewGuid().ToString("N")
  }
}

function Write-EnvIfMissing {
  param([string]$Path, [string]$Content)
  if (-not (Test-Path $Path)) {
    [System.IO.File]::WriteAllText((Join-Path (Get-Location) $Path), $Content)
    Write-Log "Generated $Path"
  } else {
    Write-Warn "$Path already exists - leaving it untouched"
  }
}

Write-Log "Generating .env files with demo defaults..."
$JwtSecret = New-Secret

$BackendEnv = @"
# Generated by install.ps1 for the quick-start profile.
# Add OPENAI_API_KEY=... / ANTHROPIC_API_KEY=... here to leave MOCK_LLM mode.
DEPLOYMENT_ENV=development
DEPLOYMENT_PROFILE=quick-start
DATABASE_URL=postgresql://scout:changeme@localhost:5432/scout
REDIS_URL=redis://localhost:6379/0
CELERY_BROKER_URL=redis://localhost:6379/1
CELERY_RESULT_BACKEND=redis://localhost:6379/2
QDRANT_URL=http://localhost:6333
QDRANT_ENABLED=false
PGVECTOR_ENABLED=true
CELERY_ENABLED=true
MOCK_LLM=true
JWT_SECRET=$JwtSecret
JWT_ALGORITHM=HS256
JWT_EXPIRATION_MINUTES=1440
BILLING_ENABLED=false
"@

$FrontendEnv = @"
NEXT_PUBLIC_API_URL=http://localhost:8000
NEXT_PUBLIC_WS_URL=ws://localhost:8000/ws
"@

Write-EnvIfMissing -Path "backend\.env" -Content $BackendEnv
Write-EnvIfMissing -Path "frontend\.env" -Content $FrontendEnv

# ─── Bring up the stack ──────────────────────────────────────────────────────
Write-Log "Building and starting the quick-start profile (first build can take a few minutes)"
docker compose -f $ComposeFile --profile $ComposeProfile up -d --build
if ($LASTEXITCODE -ne 0) { Die "docker compose up failed. See output above." }

# ─── Wait for /health/ready ──────────────────────────────────────────────────
Write-Log "Waiting for backend readiness (http://localhost:8000/health/ready)"
$ready = $false
for ($i = 0; $i -lt 120; $i++) {
  try {
    $body = (Invoke-RestMethod -Uri "http://localhost:8000/health/ready" -TimeoutSec 3)
    if ($body.status -eq "healthy") { $ready = $true; break }
  } catch {
    Start-Sleep -Seconds 2
  }
  Start-Sleep -Seconds 2
}
if (-not $ready) {
  Die "Timed out waiting for /health/ready. Run: docker compose -f $ComposeFile --profile $ComposeProfile logs backend"
}
Write-Log "Backend is healthy."

# ─── Seed demo data ──────────────────────────────────────────────────────────
Write-Log "Seeding demo organization + chatbot (this triggers a knowledge-source sync)"
docker compose -f $ComposeFile --profile $ComposeProfile exec -T backend python scripts/seed_demo.py
if ($LASTEXITCODE -ne 0) { Die "Seeding failed. See output above." }

# ─── Summary ─────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "┌──────────────────────────────────────────────────────────┐" -ForegroundColor Cyan
Write-Host "│  Scout.io is running                                     │" -ForegroundColor Cyan
Write-Host "├──────────────────────────────────────────────────────────┤" -ForegroundColor Cyan
Write-Host "│  Dashboard:   http://localhost:3000                     │" -ForegroundColor Cyan
Write-Host "│  API docs:    http://localhost:8000/docs                │" -ForegroundColor Cyan
Write-Host "│  Demo login:  $DemoEmail  (password: $DemoPassword)" -ForegroundColor Cyan
Write-Host "│  Vector store: pgvector (Qdrant excluded in quick-start)│" -ForegroundColor Cyan
Write-Host "│  LLM:         MOCK_LLM mode (add API keys to upgrade)   │" -ForegroundColor Cyan
Write-Host "└──────────────────────────────────────────────────────────┘" -ForegroundColor Cyan

Write-Log "Opening the dashboard in your browser"
Start-Process "http://localhost:3000"