#!/usr/bin/env bash
# ─── Scout.io Quick-Start Installer ──────────────────────────────────────────
# Brings up a minimal Scout.io stack (Postgres+pgvector, Redis, backend API,
# Celery worker, Next.js dashboard) with a seeded demo chatbot.
#
#   curl -fsSL https://raw.githubusercontent.com/VForge-Tech/Scout.io/main/scripts/install.sh | bash
#   # or from a local checkout:
#   ./scripts/install.sh
#
# Requires: Docker + Docker Compose plugin, git, curl. No .env editing needed —
# demo defaults are generated for you. LLM/embedding calls run in deterministic
# MOCK_LLM mode unless you set OPENAI_API_KEY/ANTHROPIC_API_KEY in backend/.env.
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/VForge-Tech/Scout.io.git}"
REPO_DIR="${REPO_DIR:-scout.io}"
COMPOSE_FILE="docker/docker-compose.quickstart.yml"
PROFILE="quick-start"
JWT_SECRET=""
DEMO_EMAIL="demo@scout.io"
DEMO_PASSWORD="DemoPass123!"

log()  { printf "\n\033[1;32m==>\033[0m %s\n" "$*"; }
warn() { printf "\033[1;33m[!]\033[0m %s\n" "$*"; }
die()  { printf "\033[1;31m[!]\033[0m %s\n" "$*" >&2; exit 1; }

# ─── Prerequisite checks ─────────────────────────────────────────────────────
check_prereqs() {
  command -v docker >/dev/null 2>&1 || die "Docker not found. Install Docker Desktop first: https://www.docker.com/products/docker-desktop/"
  docker compose version >/dev/null 2>&1 || die "Docker Compose plugin (v2) not found. Enable it in Docker Desktop settings."
  command -v git >/dev/null 2>&1 || die "git not found. Install it, or set REPO_DIR to an existing checkout."
  command -v curl >/dev/null 2>&1 || warn "curl not found — the readiness check will be skipped."
}

# ─── Locate / clone the repo ─────────────────────────────────────────────────
locate_repo() {
  if [ -f "$PWD/$COMPOSE_FILE" ]; then
    log "Using current directory as the Scout.io checkout: $PWD"
    return 0
  fi
  if [ -d "$REPO_DIR" ]; then
    log "Updating existing checkout in $REPO_DIR"
    git -C "$REPO_DIR" pull --ff-only
    cd "$REPO_DIR"
    return 0
  fi
  log "Cloning Scout.io from $REPO_URL"
  git clone --depth 1 "$REPO_URL" "$REPO_DIR"
  cd "$REPO_DIR"
}

# ─── Generate .env files ─────────────────────────────────────────────────────
write_env() {
  local path="$1"
  local content="$2"
  if [ ! -f "$path" ]; then
    printf '%s' "$content" > "$path"
    log "Generated $path"
  else
    warn "$path already exists — leaving it untouched"
  fi
}

gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

setup_envs() {
  JWT_SECRET="$(gen_secret)"

  local backend_env
  backend_env="# Generated by install.sh for the quick-start profile.\n# Add OPENAI_API_KEY=... / ANTHROPIC_API_KEY=... here to leave MOCK_LLM mode.\nDEPLOYMENT_ENV=development\nDEPLOYMENT_PROFILE=quick-start\nDATABASE_URL=postgresql://scout:changeme@localhost:5432/scout\nREDIS_URL=redis://localhost:6379/0\nCELERY_BROKER_URL=redis://localhost:6379/1\nCELERY_RESULT_BACKEND=redis://localhost:6379/2\nQDRANT_URL=http://localhost:6333\nQDRANT_ENABLED=false\nPGVECTOR_ENABLED=true\nCELERY_ENABLED=true\nMOCK_LLM=true\nJWT_SECRET=${JWT_SECRET}\nJWT_ALGORITHM=HS256\nJWT_EXPIRATION_MINUTES=1440\nBILLING_ENABLED=false\n"
  write_env "backend/.env" "$backend_env"

  local frontend_env
  frontend_env="NEXT_PUBLIC_API_URL=http://localhost:8000\nNEXT_PUBLIC_WS_URL=ws://localhost:8000/ws\n"
  write_env "frontend/.env" "$frontend_env"
}

# ─── Bring up the stack ──────────────────────────────────────────────────────
compose_up() {
  log "Building and starting the quick-start profile (first build can take a few minutes)"
  docker compose -f "$COMPOSE_FILE" --profile "$PROFILE" up -d --build
}

# ─── Wait for /health/ready ──────────────────────────────────────────────────
wait_ready() {
  if ! command -v curl >/dev/null 2>&1; then
    warn "Skipping readiness wait (curl missing). Give the backend ~30s, then open http://localhost:3000"
    return 0
  fi
  log "Waiting for backend readiness (http://localhost:8000/health/ready)"
  for _ in $(seq 1 120); do
    local body status
    body="$(curl -fsS http://localhost:8000/health/ready 2>/dev/null || true)"
    status="$(printf '%s' "$body" | grep -o '"status"[^,]*' | head -n1 || true)"
    if [ "${body#*\"healthy\"}" != "$body" ] || [ "${status#*healthy}" != "$status" ]; then
      log "Backend is healthy."
      return 0
    fi
    sleep 2
  done
  die "Timed out waiting for /health/ready. Run: docker compose -f $COMPOSE_FILE --profile $PROFILE logs backend"
}

# ─── Seed demo data ──────────────────────────────────────────────────────────
seed_demo() {
  log "Seeding demo organization + chatbot (this triggers a knowledge-source sync)"
  docker compose -f "$COMPOSE_FILE" --profile "$PROFILE" exec -T backend python scripts/seed_demo.py
}

open_dashboard() {
  log "Opening the dashboard in your browser"
  if command -v xdg-open >/dev/null 2>&1; then
    (xdg-open http://localhost:3000 >/dev/null 2>&1 &) || true
  elif command -v open >/dev/null 2>&1; then
    open http://localhost:3000 || true
  elif [ "$OSTYPE" = "msys" ] || [ "$OSTYPE" = "win32" ]; then
    cmd.exe /c start http://localhost:3000 || true
  else
    warn "Open http://localhost:3000 manually."
  fi
}

print_summary() {
  printf '\n'
  printf '┌──────────────────────────────────────────────────────────┐\n'
  printf '│  Scout.io is running                                     │\n'
  printf '├──────────────────────────────────────────────────────────┤\n'
  printf '│  Dashboard:   http://localhost:3000                     │\n'
  printf '│  API docs:    http://localhost:8000/docs                │\n'
  printf '│  Demo login:  %s  (password: %s)\n' "$DEMO_EMAIL" "$DEMO_PASSWORD"
  printf '│  Vector store: pgvector (Qdrant excluded in quick-start)│\n'
  printf '│  LLM:         MOCK_LLM mode (add API keys to upgrade)   │\n'
  printf '└──────────────────────────────────────────────────────────┘\n'
}

main() {
  check_prereqs
  locate_repo
  setup_envs
  compose_up
  wait_ready
  seed_demo
  print_summary
  open_dashboard
}

main "$@"